Repository IU-Capstone-Project-2025/open-labs-share, pull requests merged in 2025-06, with the labels that each got.

#30 feat(frontend): add frontend project structure
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/favicon.ico
  frontend/src/App.jsx
  frontend/src/assets/img.png
  frontend/src/components/Button.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/RegistrationPage.jsx
  frontend/tailwind.config.js
  frontend/vite.config.js
Labels: enhancement

#48 Set up api gateway
  README.md
  services/api-gateway/README_API_GATEWAY.md
Labels: documentation

#59 Implement User Authentication and Data Retrieval API
  services/api-gateway/.env.example
  services/api-gateway/.gitattributes
  services/api-gateway/.gitignore
  services/api-gateway/DEPLOY.md
  services/api-gateway/Dockerfile
  services/api-gateway/build.gradle
  services/api-gateway/docker-compose.yml
  services/api-gateway/gradle/wrapper/gradle-wrapper.jar
  services/api-gateway/gradle/wrapper/gradle-wrapper.properties
  services/api-gateway/gradlew
  services/api-gateway/gradlew.bat
  services/api-gateway/settings.gradle
  services/api-gateway/src/main/java/olsh/backend/api_gateway/ApiGatewayApplication.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/annotation/RequireAuth.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/config/GrpcClientConfig.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/config/JacksonConfig.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/config/WebConfig.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/controller/UserController.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/dto/response/UserResponse.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/exception/AuthenticationException.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/exception/ErrorResponse.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/exception/GlobalExceptionHandler.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/exception/UserAlreadyExistsException.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/exception/UserInvalidPasswordException.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/exception/UserNotFoundException.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/AuthServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/UserServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/model/AuthValidationResponse.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/model/UserData.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/model/UserInfo.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/interceptor/AuthInterceptor.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/AuthService.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/UserService.java
  services/api-gateway/src/main/proto/auth.proto
  services/api-gateway/src/main/proto/user.proto
  services/api-gateway/src/main/resources/application.yml
Labels: enhancement, design

#86 Fix data transfer in Lab Service
  services/labs-service/labs.proto
  services/labs-service/submissions.proto
Labels: design

#154 Proto validation and sync pipeline
  .github/workflows/proto-validation.yml
  scripts/PROTO_VALIDATION.md
  scripts/sync-proto.sh
  scripts/validate-proto.sh
  services/api-gateway/src/main/proto/articles_service.proto
  services/api-gateway/src/main/proto/auth.proto
  services/api-gateway/src/main/proto/auth_service.proto
  services/api-gateway/src/main/proto/feedback_service.proto
  services/api-gateway/src/main/proto/labs.proto
  services/api-gateway/src/main/proto/labs_service.proto
  services/api-gateway/src/main/proto/user.proto
  services/articles-service/articles_service.proto
  services/auth-service/src/main/proto/users_service.proto
  services/feedback-service/api/feedback_service.proto
  services/labs-service/app/proto/labs_service.proto
  services/labs-service/app/proto/submissions_service.proto
Labels: enhancement

#155 Develop Articles Service
  services/articles-service/ARTICLES_README.md
  services/articles-service/app/.env.example
  services/articles-service/app/Dockerfile
  services/articles-service/app/client.py
  services/articles-service/app/config.py
  services/articles-service/app/db/init-down.sql
  services/articles-service/app/db/init-up.sql
  services/articles-service/app/docker-compose.yml
  services/articles-service/app/main.py
  services/articles-service/app/proto/articles_service.proto
  services/articles-service/app/requirements.txt
  services/articles-service/app/utils/models.py
Labels: enhancement
