Repository IU-Capstone-Project-2025/open-labs-share, pull requests merged in 2025-07, with the labels that each got.

#185 Create tests for labs service
  services/labs-service/app/client.py
  services/labs-service/app/tester.py
  services/labs-service/app/utils/models.py
  services/labs-service/requirements.txt
Labels: enhancement

#234 Create gRPC method GetPossibleToReviewSubmissions at Labs Service
  services/api-gateway/src/main/proto/submissions_service.proto
  services/labs-service/app/proto/submissions_service.proto
  services/labs-service/app/services/submissions_service.py
Labels: enhancement

#236 Fix docker-compose build on dev
  docker-compose.yml
Labels: bug

#243 Enhance search with tags and title text
  services/api-gateway/API_README.md
  services/api-gateway/src/main/java/olsh/backend/api_gateway/controller/ArticleController.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/controller/LabController.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/dto/StringMapper.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/dto/request/ArticlesGetRequest.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/dto/request/LabCreateRequest.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/dto/request/LabsGetRequest.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/dto/response/ArticleListResponse.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/ArticleServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/LabServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/ArticleService.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/LabService.java
  services/api-gateway/src/test/java/olsh/backend/api_gateway/dto/ArticlesGetRequestTest.java
  services/api-gateway/src/test/java/olsh/backend/api_gateway/dto/LabsGetRequestTest.java
Labels: enhancement

#246 Add LaTeX support for .md on frontend
  frontend/package.json
  frontend/src/pages/LabPage.jsx
Labels: enhancement, design

#245 Comment sections on Frontend
  .env.example
  .github/workflows/ci-go-feedback-service.yml
  .github/workflows/ci-java-auth-service.yml
  .github/workflows/ci-java-gateway.yml
  .github/workflows/ci-java-users-service.yml
  .github/workflows/ci-ml-service.yml
  .github/workflows/ci-python-articles-service.yml
  .github/workflows/ci-python-labs-service.yml
  docker-compose.yml
  frontend/src/App.jsx
  frontend/src/components/CommentsSection.jsx
  frontend/src/pages/LabPage.jsx
  frontend/src/pages/ReviewQueuePage.jsx
  frontend/src/utils/api.js
  scripts/deploy_green.sh
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/CommentService.java
  services/feedback-service/internal/grpc/server/comment.go
  services/feedback-service/internal/grpc/server/feedback.go
  services/feedback-service/internal/repository/comment.go
  services/feedback-service/internal/service/comment.go
  services/feedback-service/internal/service/feedback.go
Labels: enhancement, design

#249 Marimo elements research
  services/marimo-service/DB_DESCR.md
  services/marimo-service/FAQ.md
  services/marimo-service/MARIMO_README.md
  services/marimo-service/MARIMO_SHORT_DESCR.md
  services/marimo-service/build.gradle
  services/marimo-service/src/main/java/olsh/backend/marimoservice/MarimoServiceApplication.java
  services/marimo-service/src/main/proto/marimo_service.proto
  services/marimo-service/src/main/resources/application.yml
  services/marimo-service/src/main/resources/schema.sql
Labels: documentation

#261 Create articles service tests
  services/articles-service/app/client.py
  services/articles-service/app/main.py
  services/articles-service/app/requirements.txt
  services/articles-service/app/tester.py
Labels: enhancement

#264 Marp support for Labs
  frontend/package.json
  frontend/src/components/MarpRenderer.jsx
  frontend/src/pages/LabPage.jsx
Labels: enhancement, design

#266 Docs for api gateway
  services/api-gateway/.env.example
  services/api-gateway/DEPLOY.md
  services/api-gateway/README.md
  services/api-gateway/src/main/java/olsh/backend/api_gateway/config/GrpcClientConfig.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/ArticleServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/AuthServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/CommentServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/LabServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/SubmissionServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/UserServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/ArticleService.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/AuthService.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/CommentService.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/FeedbackService.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/LabService.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/SubmissionService.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/TimestampConverter.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/UserService.java
  services/api-gateway/src/main/resources/application.yml
Labels: documentation

#282 Fix autograding frontend
  frontend/src/pages/LabPage.jsx
  frontend/src/pages/SubmissionPage.jsx
Labels: enhancement, design

#295 Marimo last value in cell output
  frontend/src/components/MarimoCell.jsx
  frontend/src/components/MarimoOutput.jsx
  frontend/src/components/OutputRenderer.jsx
  services/marimo-service/marimo-executor-service/main.py
  services/marimo-service/marimo-executor-service/marimo_executor_service_pb2.py
  services/marimo-service/marimo-executor-service/marimo_executor_service_pb2_grpc.py
  services/marimo-service/marimo-executor-service/proto/marimo_executor_service.proto
  services/marimo-service/marimo-executor-service/requirements.txt
  services/marimo-service/marimo-executor-service/service/executor.py
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/CellOutputDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/service/ExecutionService.java
  services/marimo-service/marimo-manager-service/src/main/proto/marimo_executor_service.proto
Labels: enhancement, design

#298 GetArticlesCount grpc endpoint
  services/api-gateway/src/main/proto/articles_service.proto
  services/articles-service/app/main.py
  services/articles-service/app/proto/articles_service.proto
  services/marimo-service/marimo-manager-service/src/main/proto/articles_service.proto
Labels: enhancement

#301 Statistics endpoint in api gateway
  services/api-gateway/API_README.md
  services/api-gateway/src/main/java/olsh/backend/api_gateway/controller/StatisticsController.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/dto/response/StatisticsResponse.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/ArticleServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/LabServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/SubmissionServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/grpc/client/UserServiceClient.java
  services/api-gateway/src/main/java/olsh/backend/api_gateway/service/StatisticsService.java
Labels: enhancement

#304 Marimo widgets
  docs/MARIMO_WIDGET_FLOW_ANALYSIS.md
  frontend/docs/WIDGET_INTERACTION_BEHAVIOR.md
  frontend/src/components/MarimoCell.jsx
  frontend/src/components/OutputRenderer.jsx
  frontend/src/components/ResizablePanel.jsx
  frontend/src/components/WidgetErrorBoundary.jsx
  frontend/src/components/WidgetRenderer.jsx
  frontend/src/components/widgets/ButtonWidget.jsx
  frontend/src/components/widgets/DropdownWidget.jsx
  frontend/src/components/widgets/MultiselectWidget.jsx
  frontend/src/components/widgets/NumberWidget.jsx
  frontend/src/components/widgets/PlotlyWidget.jsx
  frontend/src/components/widgets/RadioWidget.jsx
  frontend/src/components/widgets/RangeSliderWidget.jsx
  frontend/src/components/widgets/SliderWidget.jsx
  frontend/src/components/widgets/SwitchWidget.jsx
  frontend/src/components/widgets/TableWidget.jsx
  frontend/src/components/widgets/TextAreaWidget.jsx
  frontend/src/contexts/MarimoSessionContext.jsx
  frontend/src/contexts/WidgetStateContext.jsx
  frontend/src/utils/api.js
  frontend/src/utils/widgetCollaboration.js
  frontend/src/utils/widgetPersistence.js
  frontend/src/utils/widgetTemplates.js
  frontend/src/utils/widgetUtils.js
  services/marimo-service/docs/IMPLEMENTATION_SUMMARY.md
  services/marimo-service/docs/MARIMO_WIDGETS_PLAN.md
  services/marimo-service/docs/WIDGET_FLOW_ANALYSIS.md
  services/marimo-service/marimo-executor-service/main.py
  services/marimo-service/marimo-executor-service/marimo_executor_service_pb2.py
  services/marimo-service/marimo-executor-service/marimo_executor_service_pb2_grpc.py
  services/marimo-service/marimo-executor-service/proto/marimo_executor_service.proto
  services/marimo-service/marimo-executor-service/proto/marimo_executor_service_pb2.py
  services/marimo-service/marimo-executor-service/proto/marimo_executor_service_pb2_grpc.py
  services/marimo-service/marimo-executor-service/service/executor.py
  services/marimo-service/marimo-executor-service/service/session.py
  services/marimo-service/marimo-executor-service/service/widget_executor.py
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/config/JacksonConfig.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/controller/MarimoController.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/entity/WidgetState.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/grpc/client/PythonMarimoServiceClient.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/BatchUpdateResponseDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/BatchUpdateWidgetsRequestDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/UpdateWidgetValueRequestDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/WidgetAnalyticsDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/WidgetCollaborationDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/WidgetConstraintsDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/WidgetPersistenceRequestDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/WidgetStateDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/WidgetTemplateDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/model/dto/WidgetVersionDto.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/repository/WidgetStateRepository.java
  services/marimo-service/marimo-manager-service/src/main/java/olsh/backend/marimomanagerservice/service/ExecutionService.java
  services/marimo-service/marimo-manager-service/src/main/proto/marimo_executor_service.proto
Labels: enhancement, design
